android-AAR-minapi16:
  rules:
    - if: $PROJECT_HAVE_STORAGE50_RUNNERS == "true"
  image: registry.gitlab.com/retroshare/retroshare:android_aar_base_16_build
  script:
    - > 
      ./gradlew build publish
      -Dorg.gradle.project.buildDir=/libretroshare-build/
      -PANDROID_MIN_API_LEVEL=16
      -PLIBRETROSHARE_SOURCE_VERSION="$CI_COMMIT_SHORT_SHA"
      -PNATIVE_TOOLCHAINS_DIR="/libretroshare-native-toolchains/"
  tags:
    - storage50

android-AAR-minapi21:
  rules:
    - if: $PROJECT_HAVE_STORAGE50_RUNNERS == "true"
  image: registry.gitlab.com/retroshare/retroshare:android_aar_base_21
  script:
    - > 
      ./gradlew build publish
      -Dorg.gradle.project.buildDir=/libretroshare-build/
      -PANDROID_MIN_API_LEVEL=21
      -PLIBRETROSHARE_SOURCE_VERSION="$CI_COMMIT_SHORT_SHA"
      -PNATIVE_TOOLCHAINS_DIR="/libretroshare-native-toolchains/"
  tags:
    - storage50

android-AAR-minapi24:
  rules:
    - if: $PROJECT_HAVE_STORAGE50_RUNNERS == "true"
  image: registry.gitlab.com/retroshare/retroshare:android_aar_base_24
  script:
    - > 
      ./gradlew build publish
      -Dorg.gradle.project.buildDir=/libretroshare-build/
      -PANDROID_MIN_API_LEVEL=24
      -PLIBRETROSHARE_SOURCE_VERSION="$CI_COMMIT_SHORT_SHA"
      -PNATIVE_TOOLCHAINS_DIR="/libretroshare-native-toolchains/"
  tags:
    - storage50

android-minapi16_armeabi-v7a_bundleDebugAar:
  rules:
    - if: $PROJECT_HAVE_STORAGE50_RUNNERS != "true"
  image: registry.gitlab.com/retroshare/retroshare:android_aar_base_16_armeabi-v7a_bundleDebugAar
  script:
    - > 
      ./gradlew bundleDebugAar
      -Dorg.gradle.project.buildDir=/libretroshare-build/
      -PANDROID_MIN_API_LEVEL=16
      -PLIBRETROSHARE_SOURCE_VERSION="$CI_COMMIT_SHORT_SHA"
      -PNATIVE_TOOLCHAINS_DIR="/libretroshare-native-toolchains/"
